### ISSUE TITLE
예제 실행시 오류 발생

### ISSUE THREAD

**Issue by nao728** [BriZainer/OpenXMLExamples#12]
![example_execute_error](https://user-images.githubusercontent.com/17330056/33003368-a8ac148c-cdfd-11e7-85ec-e32e9a30b5b9.png)

'D:\git\OpenXMLExamples\OpenXMLExamples\bin\Debug\output' 경로의 일부를 찾을 수 없습니다.

**Comment by BriZainer** [comment]
프로그램 시작 시 output폴더 생성 코드 추가
